### ISSUE TITLE
Videos with slashes in their title are failing

### ISSUE THREAD

**Issue by Flet** [itaisteinherz/videos#1]
I suspect its here:
https://github.com/itaisteinherz/videos/blob/master/index.js#L109

Maybe this something like: `title.replace(new RegExp(path.sep, 'g'),'')`

**Comment by Flet** [comment]
Here is an example video with a slash in its name that fails: https://www.youtube.com/watch?v=OZ60KLh3I18

**Comment by itaisteinherz** [comment]
Sorry for the inactivity, I've been busy lately but the issue should be fixed in `v1.1.1`. If you encounter any other issues down the road I'll be more than happy to help.
